language: python
python:
  - 3.11
install:
  - pip install -r requirements-dev.txt
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - flake8
  - pytest libpythonpro_lucas --cov=libpythonpro_lucas
after_success:
  - codecov